---
apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash-quickstart
  namespace: default
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch-quickstart
      clusterName: elasticsearch-quickstart
  version: 8.8.0